version: '3'

services:
  mongodb:
    image: 'mongo:latest'    
    container_name: challenge_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:     
      - MONGO_INITDB_DATABASE=schoolsdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=lbccodechallengesecret
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
